### ISSUE TITLE
bin function end, some statement can be a function && others.

### ISSUE THREAD

**Issue by IvanaXu** [statcompute/py_mob#3]
- bin function end, some statement can be a function. 

https://github.com/statcompute/py_mob/blob/cda01475df173d8f8e003b49636fe818581c0b08/py_mob/py_mob.py#L293-L309

- Nice.

https://github.com/statcompute/py_mob/blob/cda01475df173d8f8e003b49636fe818581c0b08/py_mob/py_mob.py#L189-L190

- trying to run data.

- **BTW**, the new bin function(kmn_bin、gbm_bin) it is great.

**Comment by statcompute** [comment]
I agree. the rule parsing is not compact. let me think about it and see  if it can be wrapped into a function.

**Comment by statcompute** [comment]
generating rules has been wrapped in a function in the  updated version. thanks for the suggestion.
